name: 'aws-waf-temp-access'
description: 'Add GitHub Runner IP to AWS WAF IPSet with automatic cleanup'
author: 'digglife'

# GitHub Marketplace metadata
branding:
  icon: 'shield'
  color: 'orange'

inputs:
  id:
    description: 'The ID of the IPSet'
    required: true
  name:
    description: 'The name of the IPSet'
    required: true
  scope:
    description: 'The scope of the IPSet (CLOUDFRONT or REGIONAL)'
    required: true
    default: 'REGIONAL'
  region:
    description: 'The AWS region for the IPSet'
    required: true
    default: 'us-east-1'

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/cleanup.js'

outputs:
  ip-address:
    description: 'The public IP address that was added to the IPSet'
  status:
    description: 'Status of the operation (success or failed)'