name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Run linter
        run: npm run lint

      - name: Build action
        run: npm run build

      - name: Verify dist files
        run: |
          if [ ! -f "dist/index.js" ] || [ ! -f "dist/cleanup.js" ]; then
            echo "Error: dist files are missing"
            exit 1
          fi
          echo "✅ All dist files are present"

      - name: Extract tag name
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.tag }}
          name: Release ${{ steps.tag.outputs.tag }}
          body: |
            ## Changes in ${{ steps.tag.outputs.tag }}

            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for detailed changes.

            ## Usage

            ```yaml
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::123456789012:role/github-actions-role
                aws-region: us-east-1
            - name: Add runner IP to WAF IPSet
              uses: digglife/aws-waf-ipset-update@${{ steps.tag.outputs.tag }}
              with:
                id: 'your-ipset-id'
                name: 'your-ipset-name'
                scope: 'REGIONAL'
                region: 'us-east-1'
            ```
          draft: false
          prerelease: false

      - name: Commit and push dist files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/
          if ! git diff --staged --quiet; then
            git commit -m "Build and package for release ${{ steps.tag.outputs.tag }}"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
